@extends('layouts.main-layout')
@section('head')
    <title>Home</title>
@endsection
@section('content')
    <h1>Comic:</h1>
    <ul> 
        <li>{{$comic->title}}</li>
        <li>{{$comic->years}}</li>
        <li>{{$comic->author}}</li>   
        <li>{{$comic->publisher}}</li>  
        <li>{{$comic->illustrator}}</li> 
        <li>{{$comic->genre}}</li>
        <li>{{$comic->edition_number}}</li>
        <li>{{$comic->value}}</li>
    </ul>
@endsection
